#!/bin/bash

#  SimpleArchInstaller is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  SimpleArchInstaller is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License
#  along with SimpleArch Installer.  If not, see <https://www.gnu.org/licenses/>.

# Credits
#https://gist.github.com/mattiaslundberg/8620837
#https://gist.github.com/rasschaert/0bb7ebc506e26daee585
#https://www.howtoforge.com/tutorial/how-to-install-arch-linux-with-full-disk-encryption/
#https://computingforgeeks.com/install-arch-linux-with-lvm-on-uefi-system/
#The above resources helped me in getting this Script to where it is now

bootstrapper_dialog() {
    DIALOG_RESULT=$(dialog --clear --stdout --backtitle "SimpleArchInstaller" --no-shadow "$@" 2>/dev/null)
}

#################
#### Welcome ####
#################
bootstrapper_dialog --title "Welcome" --msgbox "Welcome to SimpleArchInstaller.\n" 6 60

##############################
#### UEFI / BIOS detection ###
##############################
efivar -l >/dev/null 2>&1

if [[ $? -eq 0 ]]; then
    UEFI_BIOS_text="UEFI detected."
    UEFI_radio="on"
    BIOS_radio="off"
else
    UEFI_BIOS_text="BIOS detected."
    UEFI_radio="off"
    BIOS_radio="on"
fi

bootstrapper_dialog --title "UEFI or BIOS" --radiolist "${UEFI_BIOS_text}\nPress <Enter> to accept." 10 30 2 1 UEFI "$UEFI_radio" 2 BIOS "$BIOS_radio"
[[ $DIALOG_RESULT -eq 1 ]] && UEFI=1 || UEFI=0

#################
#### Prompts ####
#################
bootstrapper_dialog --title "Hostname" --inputbox "Please enter a name for this host.\n" 8 60
hostname="$DIALOG_RESULT"
bootstrapper_dialog --title "Country" --inputbox "Please enter your country name.\n" 8 60
country="$DIALOG_RESULT"

bootstrapper_dialog --title "UserName" --inputbox "Please enter a name for the User.\n" 8 60
UserName="$DIALOG_RESULT"


##########################
#### Password prompts ####
##########################
bootstrapper_dialog --title "Disk encryption" --passwordbox "Please enter a strong passphrase for the full disk encryption.\n" 8 60
encryption_passphrase="$DIALOG_RESULT"

bootstrapper_dialog --title "Root password" --passwordbox "Please enter a strong password for the root user.\n" 8 60
root_password="$DIALOG_RESULT"

bootstrapper_dialog --title "User password" --passwordbox "Please enter a strong password for the user.\n" 8 60
UserPassword="$DIALOG_RESULT"

#################
#### Warning ####
#################
bootstrapper_dialog --title "WARNING" --msgbox "This script will NUKE /dev/nvme0n1 from orbit.\nPress <Enter> to continue or <Esc> to cancel.\n" 6 60
[[ $? -ne 0 ]] && (bootstrapper_dialog --title "Cancelled" --msgbox "Script was cancelled at your request." 5 40; exit 0)

##########################
#### reset the screen ####
##########################
reset

#########################################
#### Nuke and set up disk partitions ####
#########################################
echo "Zapping disk"
sgdisk --zap-all /dev/nvme0n1

if [[ $UEFI -eq 1 ]]; then

parted -s /dev/nvme0n1 mklabel gpt
parted -s /dev/nvme0n1 mkpart ESP fat32 1MiB 513MiB
parted -s /dev/nvme0n1 set 1 boot on
parted -s /dev/nvme0n1 name 1 efi
parted -s /dev/nvme0n1 mkpart primary 513MiB 800MiB
parted -s /dev/nvme0n1 name 2 boot
parted -s /dev/nvme0n1 mkpart primary 800MiB 100%
parted -s /dev/nvme0n1 name 3 lvm-partition
parted -s /dev/nvme0n1 mkpart primary fat32 1MiB 261MiB 
parted -s /dev/nvme0n1 set 1 esp on  
parted -s /dev/nvme0n1 set 3 lvm on

else
    printf "n\np\n2\n\n\nt\n2\n8e\nw\n" | fdisk /dev/nvme0n1
fi

echo "Setting up encryption"
printf "%s" "$encryption_passphrase" | cryptsetup luksFormat /dev/nvme0n1p3 -
printf "%s" "$encryption_passphrase" | cryptsetup open --type luks /dev/nvme0n1p3 lvm -

echo "Setting up LVM"
pvcreate /dev/mapper/lvm
vgcreate vg00 /dev/mapper/lvm
lvcreate -L 30G vg00 -n lvroot
lvcreate -L 20G vg00 -n lvswap
lvcreate -l +100%FREE vg00 -n lvhome

echo "Creating XFS file systems on top of logical volumes"
yes | mkfs.ext4 /dev/mapper/vg00-lvroot
yes | mkfs.xfs /dev/mapper/vg00-lvhome
yes | mkfs.vfat -F 32 /dev/nvme0n1p1
yes | mkfs.ext4 /dev/nvme0n1p2
mkswap /dev/mapper/vg00-lvswap && swapon /dev/mapper/vg00-lvswap 

######################
#### Install Arch ####
######################

if [[ $UEFI -eq 1 ]]; then

mount /dev/vg00/lvroot /mnt
mkdir /mnt/{boot,home}
mount /dev/nvme0n1p2 /mnt/boot/
mkdir /mnt/boot/efi
mount /dev/nvme0n1p1 /mnt/boot/efi
mount /dev/vg00/lvhome /mnt/home
mkdir /mnt/Data
mount /dev/sda1 /mnt/Data


else

mount /dev/vg00/lvroot /mnt
mkdir /mnt/{boot,home}
mount /dev/nvme0n11 /mnt/boot
mount /dev/vg00/lvhome /mnt/home

fi

pacman -Syy
pacman -S --noconfirm reflector
reflector --country $country  --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
pacman -Syy

yes '' | pacstrap -i /mnt base base-devel ttf-liberation

genfstab -U -p /mnt >> /mnt/etc/fstab

###############################
#### Configure base system ####
###############################
arch-chroot /mnt /bin/bash <<EOF
echo "Setting and generating locale"
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
echo "en_IN.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
export LANG=en_IN.UTF-8
echo "LANG=en_IN.UTF-8" >> /etc/locale.conf
echo "Setting time zone"
ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
echo "Setting hostname"
echo $hostname > /etc/hostname
sed -i "/localhost/s/$/ $hostname/" /etc/hosts
echo "Installing wifi packages"
## Insert Code to Modify Pacman.conf for Enabling Multilib support.

pacman --noconfirm -S networkmanager net-tools firefox qemu virt-manager dnsmasq iptables ebtables libvirt xorg-server xorg-drivers steam obs-studio shotcut vlc plasma-desktop plasma-meta konsole dolphin kwrite sddm sddm-kcm nvidia nvidia-settings lib32-nvidia-utils  
systemctl enable libvirtd
systemctl enable NetworkManager
systemctl enable sddm
echo "Generating initramfs"
sed -i 's/^HOOKS.*/HOOKS="base udev autodetect modconf block encrypt lvm2 filesystems keyboard fsck"/' /etc/mkinitcpio.conf
mkinitcpio -p linux
echo "Setting root password"
echo "root:${root_password}" | chpasswd
useradd -m -G wheel -s /bin/bash $UserName
echo "Setting user password"
echo "user:${UserPassword}" | chpasswd
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers
EOF

#############################
#### Install boot loader ####
#############################
if [[ $UEFI -eq 1 ]]; then
arch-chroot /mnt /bin/bash <<EOF
    echo "Installing Grub boot loader"
    pacman --noconfirm -S grub efibootmgr 
    grub-install 
    sed -i 's|^GRUB_CMDLINE_LINUX.*|GRUB_CMDLINE_LINUX="quiet cryptdevice=/dev/nvme0n1p3:luks:allow-discards root=/dev/vg00/lvroot"|' /etc/default/grub

       grub-mkconfig -o /boot/grub/grub.cfg
EOF

else
    arch-chroot /mnt /bin/bash <<EOF
    echo "Installing Grub boot loader"
    pacman --noconfirm -S grub
    grub-install /dev/nvme0n1
    sed -i 's|^GRUB_CMDLINE_LINUX.*|GRUB_CMDLINE_LINUX="quiet cryptdevice=/dev/nvme0n1p3:luks:allow-discards root=/dev/vg00/lvroot"|' /etc/default/grub
    
    grub-mkconfig -o /boot/grub/grub.cfg
EOF
fi

#################
#### The end ####
#################
